display_categories:
  type: list
  default: ""
  description:
    en: A list of categories where the "Board" button should appear. If left blank, it will be shown everywhere. Use @ to denote the top level view.
default_modes:
  type: list
  default: ""
  description:
    en: "Override the default board mode for each category. Use the syntax `category:mode:params`. For example, `support:assigned:david,sam,joffrey`. Use @ to denote the top level view. Use @untagged to display an untagged column."
default_view:
  type: list
  default: ""
  description:
    en: A list of categories where the "Board" is the default view. Does not yet support the top level default view.
require_confirmation:
  default: true
  description:
    en: Display a confirmation modal before making changes to a topic's tags/category?
show_tags:
  default: false
  description:
    en: Show tags on topic cards?
extra_icons:
  default: "user-minus"
  description:
    en: Extra icons to load for the theme component. There is no need to change this setting.
